### ISSUE TITLE
ライセンスにつきまして

### ISSUE THREAD

**Issue by minaton** [geechsInc/Laravel-kintoneRestAPI#4]
初めまして！
新潟でkintone開発をしてる「みなとん」といいます。

まず、ここでお聞きする内容ではないかもしれないこと、ご容赦ください。

今回、laravelを使ってkintoneと連携する案件を行うことになり、ググっていたらここに辿りつきました。
ぜひ利用させていただきたいなと思っておりますが、ライセンスの記載がございませんでしたので
確認させていただきたく連絡差し上げました。

商用利用は問題ございませんでしょうか。
利用にあたり、制限や注意事項等ございましたらお教えください。

以上、よろしくお願いいたします。

**Comment by geechs-yhamada** [comment]
初めまして。
ご連絡ありがとうございます。

こちらのリポジトリは古くなっているため、最新版である下記リポジトリのものをご利用ください。
下記リポジトリはMIT ライセンスを設定しております。
https://github.com/yjhm214/Laravel-kintoneRestAPI

よろしくお願い致します。

**Comment by minaton** [comment]
geechs-yhamadaさん

お返事いただきありがとうございます。
すみません、せっかく対応していただいたのですが
急を要しており、別なライブラリを採用となりました。

別案件の開発時に改めて利用を検討させていただきます。
リポジトリの作成、公開ありがとうございました！
